In [1]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN',
'londON_StockhOlm',

'Budapest_PaRis', 'Brussels_londOn'],
'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
'12. Air France', '"Swiss Air"']})

In [2]:
df

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

# 1

In [3]:
df["FlightNumber"][1] = 10055
df["FlightNumber"][3] = 10075

C:\Users\BNB\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\BNB\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [4]:
df["FlightNumber"] = df["FlightNumber"].astype(int)

In [5]:
df["FlightNumber"].dtype

dtype('int32')

In [6]:
df

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris         10045      [23, 47]               KLM(!)
1      MAdrid_miLAN         10055            []    <Air France> (12)
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis         10075          [13]       12. Air France
4   Brussels_londOn         10085      [67, 32]          "Swiss Air"

# 2

In [7]:
from_to = [df["From_To"][i].split(sep='_') for i in range(len(df))]
from_to

[['LoNDon', 'paris'],
 ['MAdrid', 'miLAN'],
 ['londON', 'StockhOlm'],
 ['Budapest', 'PaRis'],
 ['Brussels', 'londOn']]

In [8]:
temp = pd.DataFrame(from_to,columns=["From","To"])
temp

       From         To
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn

# 3

In [9]:
for i in range(len(temp)):
    temp["From"][i] = temp["From"][i].capitalize()
    temp["To"][i] = temp["To"][i].capitalize()

In [10]:
temp

       From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London

# 4

In [11]:
df = df.drop(['From_To'],axis=1)

In [12]:
result = pd.concat([temp,df],axis=1)
result

       From         To  FlightNumber  RecentDelays              Airline
0    London      Paris         10045      [23, 47]               KLM(!)
1    Madrid      Milan         10055            []    <Air France> (12)
2    London  Stockholm         10065  [24, 43, 87]  (British Airways. )
3  Budapest      Paris         10075          [13]       12. Air France
4  Brussels     London         10085      [67, 32]          "Swiss Air"

# 5

In [13]:
a = ["delay_1","delay_2","delay_3"]

In [14]:
b=list(result["RecentDelays"])
for i in b:
    for j in range(3-len(i)):
        i.append("NaN")

In [15]:
delays_dict = {i:j for i,j in zip(a,zip(*b))}
delays_dict

{'delay_1': (23, 'NaN', 24, 13, 67),
 'delay_2': (47, 'NaN', 43, 'NaN', 32),
 'delay_3': ('NaN', 'NaN', 87, 'NaN', 'NaN')}

In [16]:
delays = pd.DataFrame(delays_dict)
delays

  delay_1 delay_2 delay_3
0      23      47     NaN
1     NaN     NaN     NaN
2      24      43      87
3      13     NaN     NaN
4      67      32     NaN

In [17]:
result = result.drop("RecentDelays",axis=1)

In [18]:
result

       From         To  FlightNumber              Airline
0    London      Paris         10045               KLM(!)
1    Madrid      Milan         10055    <Air France> (12)
2    London  Stockholm         10065  (British Airways. )
3  Budapest      Paris         10075       12. Air France
4  Brussels     London         10085          "Swiss Air"

In [19]:
final_result = pd.concat([result,delays],axis =1)
final_result

,From,To,FlightNumber,Airline,delay_1,delay_2,delay_3
0,London,Paris,10045,KLM(!),23,47,NaN
1,Madrid,Milan,10055,<Air France> (12),NaN,NaN,NaN
2,London,Stockholm,10065,(British Airways. ),24,43,87
3,Budapest,Paris,10075,12. Air France,13,NaN,NaN
4,Brussels,London,10085,"""Swiss Air""",67,32,NaN